### ISSUE TITLE
Does this theme support banner?

### ISSUE THREAD

**Issue by Sciroccogti** [zhengzangw/hugo-theme-ztyblog#1]
such as the examlpe as here: [gohugo.io](https://gohugo.io/content-management/front-matter/#example-1)

**Comment by zhengzangw** [comment]
The example you give shows how to use hugo's cascade Front Matter, which does not explain what the banner is. I guess what you mean is to customize some part of the theme. Do you mean one of the following:

- Image on the homepage: it will be added in further version
- An icon for your site besides your name: it may be added
- a customized banner: not prepared yet

**Comment by Sciroccogti** [comment]
Sorry for the unspecified description.

According to the three features you listed above, the third one -- "a customized banner" is just what I meant. 

Anyway, thanks for your prompt reply.

**Comment by zhengzangw** [comment]
I see. This feature will be taken into consideration in further version.

**Comment by zhengzangw** [comment]
Set following options in markdown to set banner

- banner: /image/blog/example.jpg
- previewimage: /image/blog/example.jpg
