### ISSUE TITLE
How to use the template "friends/" ?

### ISSUE THREAD

**Issue by Sciroccogti** [zhengzangw/hugo-theme-ztyblog#12]
I used the command `hugo new friends/` and fetched the `_index.md` as below:
```markdown
+++
title = "Friend's Links"
+++

Example
[[friends]]
    name = "Fancy Pei"
    icon = "fancypei.jpg"
    url = "https://fancypei.github.io"
```

However, I got the page without being rendered as shown below:(I know how to set time correctly already)

![图片](https://user-images.githubusercontent.com/32357397/73714179-16459680-474b-11ea-96b7-08265ddc99e3.png)

I'm new to hugo (though I used to use Jekyll and Hexo), so I'm quite curious about how to use the templates correctly.

Thanks anyway.

**Comment by doowzs** [comment]
Try specifying a layout: `layout = "friends"` 

See https://github.com/zhengzangw/hugo-theme-ztyblog/blob/master/archetypes/friends.md

**Comment by Sciroccogti** [comment]
Sorry, I haven't update to the new version.

**Comment by Sciroccogti** [comment]
@doowzs THX, now I use the command `hugo new friends.md -k friends` to new a standard doc.
