### ISSUE TITLE
typo and suggestion on useCDN in config 

### ISSUE THREAD

**Issue by Sciroccogti** [zhengzangw/hugo-theme-ztyblog#13]
https://github.com/zhengzangw/hugo-theme-ztyblog/blob/fa2e18252b01b14d3f39e7b66880652a46c61401/config.toml.example#L84

It should be `./load.sh` instead of `./load.js`.

Meanwhile, the whole process seems to be:

```Bash
cd themes/ztyblog
npm install
npm i fuse.js
npm i mark.js
./load.sh
```

Though it is quite easy, I hope these lines may help someone.

**Comment by zhengzangw** [comment]
Thanks. But this theme didn't support fuse and mark loaded from local. So `npm install` is enough.
