### ISSUE TITLE
hugo serve启动错误

### ISSUE THREAD

**Issue by WangRongsheng** [zhengzangw/hugo-theme-ztyblog#16]
当我执行hugo serve后出现如下错误：
Error: Error building site: TOCSS: failed to transform "sass/main.scss" (text/x-scss): resource "scss/sass/main.scss_c7d65b6eceb0fea0354886e96cfa417e" not found in file cache

请问我该如何解决？

**Comment by zhengzangw** [comment]
请问您是否根据 https://gohugo.io/getting-started/quick-start/ 进行部署并在第三步中使用了未修改过的 hugo-theme-ztyblog？如果还有该问题，请回复

**Comment by WangRongsheng** [comment]
> 请问您是否根据 https://gohugo.io/getting-started/quick-start/ 进行部署并在第三步中使用了未修改过的 hugo-theme-ztyblog？如果还有该问题，请回复

是的  都是按照官方文档来的  这个问题貌似是很普遍存在的  但是我并没有找到解决办法

**Comment by doowzs** [comment]
我本地测试是没有问题的，环境是macOS 10.15 Catalina + `Hugo Static Site Generator v0.71.0/extended`（通过brew安装）

```
$ history
 2059  hugo new site test
 2061  cd test
 2064  git init
 2065  git submodule add https://github.com/zhengzangw/hugo-theme-ztyblog themes/ztyblog
 2066  ls
 2068  vi config.toml
 2069  hugo server
```

换了官方的最新版`Hugo Static Site Generator v0.73.0-428907CC/extended darwin/amd64 BuildDate: 2020-06-23T16:37:47Z`也没有报错

```
 2082  wget https://github.com/gohugoio/hugo/releases/download/v0.73.0/hugo_extended_0.73.0_macOS-64bit.tar.gz
 2083  x hugo_extended_0.73.0_macOS-64bit.tar.gz
 2084  cd test
 2085  ../hugo server
```

- 贴一下你的运行环境（操作系统、`hugo version`）
- Hugo是否为extended版本

**Comment by WangRongsheng** [comment]
> 我本地测试是没有问题的，环境是macOS 10.15 Catalina + `Hugo Static Site Generator v0.71.0/extended`（通过brew安装）
> 
> ```
> $ history
>  2059  hugo new site test
>  2061  cd test
>  2064  git init
>  2065  git submodule add https://github.com/zhengzangw/hugo-theme-ztyblog themes/ztyblog
>  2066  ls
>  2068  vi config.toml
>  2069  hugo server
> ```
> 
> 换了官方的最新版`Hugo Static Site Generator v0.73.0-428907CC/extended darwin/amd64 BuildDate: 2020-06-23T16:37:47Z`也没有报错
> 
> ```
>  2082  wget https://github.com/gohugoio/hugo/releases/download/v0.73.0/hugo_extended_0.73.0_macOS-64bit.tar.gz
>  2083  x hugo_extended_0.73.0_macOS-64bit.tar.gz
>  2084  cd test
>  2085  ../hugo server
> ```
> 
> * 贴一下你的运行环境（操作系统、`hugo version`）
> * Hugo是否为extended版本

我已经成功解决问题，原因是我的hugo版本是不存在extended的，后来我改用了hugo_extended_0.68.3，就可以成功运行没有问题
