### ISSUE TITLE
missing images/boat.jpg

### ISSUE THREAD

**Issue by Sciroccogti** [zhengzangw/hugo-theme-ztyblog#2]
It seems that `boat.jpg` which is used in the homepage is not contained in the theme.

**Comment by zhengzangw** [comment]
Yes, it is. We hope homepage picture can be costumized, but this part has not done yet. So we haven't added the picture into the theme. This will be solved later.
And I am sorry that maybe I have no time to update the blog theme before Chinese New Year. Feel free to propose what you want to issue and I will update afterwards.
