### ISSUE TITLE
suggestions on more paras

### ISSUE THREAD

**Issue by Sciroccogti** [zhengzangw/hugo-theme-ztyblog#6]
1. It's better to be able to add a url on the **copyright** in order to meet [the standard of ICP Accreditation](https://help.aliyun.com/document_detail/146190.html);
2. Is it possible to not to show the **git commit icon** when `enableGitInfo=false`?
~~3. How can I link one of the menu to a **absoluteURL**?(just set url to a absoluteURL!)~~
4. How can I specify the navbar-brand?

Thanks again!

**Comment by zhengzangw** [comment]
1.  Now you can add icp and security in config file
2. Now you can
3. To change navbar-brand, substitude the favicon-32.png
