### ISSUE TITLE
table rendered incorrectly

### ISSUE THREAD

**Issue by Sciroccogti** [zhengzangw/hugo-theme-ztyblog#7]
Tables in markdown such as:
```markdown
A|B|C
|:---:|:---:|---
A1|B1|C1
```
A|B|C
|:---:|:---:|---
A1|B1|C1

is rendered to be:
```html
<table>
<thead>
<tr>
<th align="center">A</th>
<th align="center">B</th>
<th>C</th>
</tr>
</thead>
<tbody>
<tr>
<td align="center">A1</td>
<td align="center">B1</td>
<td>C1</td>
</tr>
</tbody>
</table>
```
However, although both the markdown and html seems to be all right above, they don't appear to be right in hugo. Actually, they look like this:

![image](https://user-images.githubusercontent.com/32357397/71730710-d5254280-2e7d-11ea-841f-c1701412e23b.png)

May be it's because that `align="center"` has been abandoned.

**Comment by doowzs** [comment]
`align="center"` is deprecated and will not render correctly with Bootstrap tables. This is not a theme issue and you should report to [Goldmark](https://github.com/yuin/goldmark/yuin/goldmark).

See https://stackoverflow.com/questions/42682942/th-aligncenter-not-working-on-a-bootstrap-table-what-might-be-the-reason.

A quick (but bad) fix using pipe: `| replaceRE "align=\"center\"" "class=\"text-center\""`

@zhengzangw Please evaluate whether using the above regex is good.

**Comment by zhengzangw** [comment]
I think add a option to control whether fix it can be a good solution.

**Comment by Sciroccogti** [comment]
@zhengzangw Thank you for your great update! Now the tables are rendered correctly.

However, I wonder whether the option `tablecenter = false` is working functionally? I just tried to set it to `false` in curiosity, but it seems that the tables are still rendered *correctly* -- that is to say, the `:---:` ones are still centered, though it's OK with me.

**Comment by zhengzangw** [comment]
In my local test, the result is right. Maybe there are some delay on your web update.
